dirs:
    train_val_dir: "data\\simpsons_dataset"
    test_dir: "data\\kaggle_simpson_testset\\kaggle_simpson_testset"

training_parameters:
    batch_size: 64
    base_lr: 0.001
    num_epochs: 20
    random_seed: 42

output_parameters:
    out_model_directory: "model/"
    out_inference_directory: "inference/"